MODEL:
  NAME: 'vit_model'
  INPUT_CHANNEL: 3
  INPUT_H: 224
  INPUT_W: 224
  PATCH_DIM: 16
  BATCH_SIZE: 8
  DROP_OUT: 0.2
  ENCODER:
    NAME: 'encoder'
    HEADS: 8
    HEAD_BIAS : True
    HIDDEN_LAYER_SCALE: 2
    ENCODER_BLOCKS: 12
    DROP_OUT: 0.2

  MLP_HEAD:
    CATEGORIES: 'TO BE SPECIFIED'

